{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hypercloud",
    "module": "hyper",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hyper-1.1.0.aar",
          "url": "hyper-1.1.0.aar",
          "size": 3752,
          "sha512": "7cb6d9354dd9312b26be80c8798c5ea2f9ce6a7808a34928b3fdf4b67df54a9bd50fab423ed37dccf07acfcdd6299bc03564580fb1f1c0dd411a1b52e398c1c4",
          "sha256": "ec18b8abf80de7549e564b8954a1fd631b8d4c2d8c0139a749e439f963f795ba",
          "sha1": "3a7cb61635f2bd5e8d67cc9353fcac6de258e02e",
          "md5": "b9bdd1c76b38bd37b2e929c3397f7ad9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.hypercloud",
          "module": "hyper",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hyper",
              "type": "aar",
              "extension": "aar",
              "classifier": "unityLibraryRelease"
            }
          }
        }
      ],
      "files": [
        {
          "name": "hyper-1.1.0.aar",
          "url": "hyper-1.1.0.aar",
          "size": 3752,
          "sha512": "7cb6d9354dd9312b26be80c8798c5ea2f9ce6a7808a34928b3fdf4b67df54a9bd50fab423ed37dccf07acfcdd6299bc03564580fb1f1c0dd411a1b52e398c1c4",
          "sha256": "ec18b8abf80de7549e564b8954a1fd631b8d4c2d8c0139a749e439f963f795ba",
          "sha1": "3a7cb61635f2bd5e8d67cc9353fcac6de258e02e",
          "md5": "b9bdd1c76b38bd37b2e929c3397f7ad9"
        }
      ]
    }
  ]
}
